# site properties and page defaults
title: SPR战队
subtitle: 
description: 人生的第一个转折点，梦想的第一个启航点
header: images/background.jpg
header-video:
  src: images/header.mp4
  loop: true
  autoplay: true
  muted: true
# site author
footer: images/footer.jpg
proofer: true
slogan: 京中铁狮，所向披靡
# site social media and other links
links:
  email: 2786573564@qq.com
  github: https://github.com/darkcome6/SPR_WEBSITE
  bilibili: "475402455"
  wechat: DL15936443068
## jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  - scope:
      type: "awards"
    values:
      layout: award
  - scope:
      type: "events"
    values:  
      layout: event
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  - scope:
      type: "news"
    values:
      layout: post



collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  awards:
    output: true
  news:
    output: true
  projects:
    output: true
  patents:
    output: true
  events:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
